# Generated by Django 3.1.7 on 2021-05-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210519_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=120),
        ),
    ]
