# Generated by Django 3.1.7 on 2021-04-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(blank=True, default=None, max_length=60, verbose_name='ClassName')),
                ('classTitle', models.CharField(blank=True, default=None, max_length=200, verbose_name='ClassTitle')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='pkg_name')),
                ('pkg_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default='', upload_to='Sheet/images')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(blank=True, default=None, max_length=60, verbose_name='SubjectName')),
                ('SubjectTitle', models.CharField(blank=True, default=None, max_length=200, verbose_name='SubjectTitle')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClassDetails', to='home.classdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(blank=True, default=None, max_length=60, verbose_name='TopicName')),
                ('topicTitle', models.CharField(blank=True, default=None, max_length=200, verbose_name='topicTitle')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='home.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubTopicName', models.CharField(blank=True, default=None, max_length=60, verbose_name='SubTopicName')),
                ('subtopicTitle', models.CharField(blank=True, default=None, max_length=200, verbose_name='subtopicTitle')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='home.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name')),
                ('pkg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='home.package')),
            ],
        ),
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explaintitle', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='explaintitle')),
                ('body', models.TextField(blank=True, default=None, max_length=6000, verbose_name='SubTopicName')),
                ('imgBlack', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/gallery/Black/')),
                ('imgColor', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/gallery/Color/')),
                ('SubTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubTopic', to='home.subtopic')),
            ],
        ),
    ]
