# Generated by Django 3.1.7 on 2021-04-24 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='classes',
            field=models.ManyToManyField(related_name='home_package_classes', to='home.ClassDetails'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_subscriptions_package', to='home.package')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_subscriptions_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
