# Generated by Django 3.1.7 on 2021-04-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210402_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explain',
            old_name='imgBlack',
            new_name='imgBlackWhite',
        ),
        migrations.RemoveField(
            model_name='explain',
            name='imgWhite',
        ),
    ]
