# Generated by Django 3.1.7 on 2021-04-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_classdetails_explain_subject_subtopic_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(blank=True, default=None, max_length=100, verbose_name='pkg_name')),
                ('pkg_price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='explain',
            old_name='imgBlackWhite',
            new_name='imgBlack',
        ),
        migrations.RemoveField(
            model_name='explain',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='remark',
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name')),
                ('pkg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='home.package')),
            ],
        ),
    ]
