# Generated by Django 3.1.7 on 2021-04-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210403_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='explain',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='remark',
        ),
    ]
