# Generated by Django 3.1.7 on 2021-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210421_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='feature_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name'),
        ),
    ]
