# Generated by Django 3.1.7 on 2021-04-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210425_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='explain',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
    ]
