# Generated by Django 3.1.7 on 2021-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_package_feature_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='feature_name',
            new_name='feature_name_1',
        ),
        migrations.AddField(
            model_name='package',
            name='feature_name_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name'),
        ),
        migrations.AddField(
            model_name='package',
            name='feature_name_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name'),
        ),
        migrations.AddField(
            model_name='package',
            name='feature_name_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name'),
        ),
        migrations.AddField(
            model_name='package',
            name='feature_name_5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name'),
        ),
    ]
