# Generated by Django 3.1.7 on 2021-04-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210425_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explain',
            name='SubTopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_explain_subtopic', to='home.subtopic'),
        ),
    ]
