# Generated by Django 3.1.7 on 2021-04-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_features_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='pkg_name')),
                ('pkg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='home.package')),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
    ]
