# Generated by Django 3.1.7 on 2021-04-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210421_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='feature_name_1',
            new_name='feature_1',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='feature_name_2',
            new_name='feature_2',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='feature_name_3',
            new_name='feature_3',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='feature_name_4',
            new_name='feature_4',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='feature_name_5',
            new_name='feature_5',
        ),
    ]
