# Generated by Django 3.1.7 on 2021-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210428_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_feature_1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_6',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
    ]
