# Generated by Django 3.1.7 on 2021-04-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210421_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='feature_1',
            new_name='pkg_feature',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_10',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_11',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_12',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_3',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_4',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_5',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_6',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_7',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_8',
        ),
        migrations.RemoveField(
            model_name='package',
            name='feature_9',
        ),
    ]
