# Generated by Django 3.1.7 on 2021-04-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210430_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='district',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='state',
        ),
    ]
