# Generated by Django 3.1.7 on 2021-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210430_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_price_disscount',
            field=models.IntegerField(default=None),
        ),
    ]
