# Generated by Django 3.1.7 on 2021-04-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
