# Generated by Django 3.1.7 on 2021-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210421_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pkg_feature',
            new_name='pkg_feature_1',
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_10',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_11',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_5',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_6',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_7',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_8',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='pkg_feature_9',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
    ]
