# Generated by Django 3.1.7 on 2021-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_package_pkg_price_disscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
