# Generated by Django 3.1.7 on 2021-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210421_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_feature_12',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='feature'),
        ),
    ]
