# Generated by Django 3.1.7 on 2021-04-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_package_pkg_feature_12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_10',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_11',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_12',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_7',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_8',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pkg_feature_9',
        ),
    ]
