# Generated by Django 3.1.7 on 2021-05-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210526_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pkg_price_percentage',
            field=models.IntegerField(null=True),
        ),
    ]
