# Generated by Django 3.1.7 on 2021-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210423_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='remark',
            field=models.TextField(blank=True, default=None, max_length=600, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='subject',
            name='remark',
            field=models.TextField(blank=True, default=None, max_length=600, verbose_name='remark'),
        ),
    ]
