# Generated by Django 3.1.7 on 2021-05-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210513_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdetails',
            name='freeForAll',
        ),
        migrations.RemoveField(
            model_name='explain',
            name='freeForAll',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='freeForAll',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='freeForAll',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='freeForAll',
        ),
    ]
