# Generated by Django 3.1.7 on 2021-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210513_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='explain',
            name='freeForAll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
    ]
