# Generated by Django 3.1.7 on 2021-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210513_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdetails',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='freeForAll',
            field=models.BooleanField(default=True),
        ),
    ]
